name: "Close Stale Issues"

on:
  schedule:
  - cron: "0 6 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Stale issue job
    steps:
    - uses: aws-actions/stale-issue-cleanup@v6
      with:
        ancient-issue-message: This issue has not received any attention in 1 year.  If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
        stale-issue-message: This issue has not received a response in a while. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
        stale-pr-message: This PR has not received a response in a while. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.

        stale-issue-label: closing-soon
        exempt-issue-labels: no-autoclose
        stale-pr-label: closing-soon
        exempt-pr-labels: no-autoclose
        response-requested-label: response-requested
        closed-for-staleness-label: closed-for-staleness

        days-before-stale: 4
        days-before-close: 7
        days-before-ancient: 365
        minimum-upvotes-to-exempt: 5

        repo-token: ${{ secrets.GITHUB_TOKEN }}
        loglevel: DEBUG