name: "Close Stale Issues"

on:
  schedule:
  - cron: "0 */4 * * *"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    name: Stale issue job
    steps:
    - uses: aws-actions/stale-issue-cleanup@v6
      with:
        ancient-issue-message: Greetings! It looks like this issue has not been active in longer than one year. We encourage you to check if this is still an issue in the latest release. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
        stale-issue-message: Greetings! It looks like this issue has not received a response in longer than four days. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.
        stale-pr-message: Greetings! It looks like this PR has not received a response in longer than four days. If you want to keep this issue open, please leave a comment below and auto-close will be canceled.

        stale-issue-label: closing-soon
        exempt-issue-labels: no-autoclose
        stale-pr-label: closing-soon
        exempt-pr-labels: no-autoclose
        response-requested-label: response-requested
        closed-for-staleness-label: closed-for-staleness

        days-before-stale: 4
        days-before-close: 7
        days-before-ancient: 365
        minimum-upvotes-to-exempt: 5

        repo-token: ${{ secrets.GITHUB_TOKEN }}
        loglevel: DEBUG
        # Set dry-run to true to not perform label or close actions.
        dry-run: false